### ISSUE TITLE
Wiki Is Broken

### ISSUE THREAD

**Issue by GrahamCampbell** [CHH/php-build#268]
https://i.starbs.net/v8OZ

**Comment by GrahamCampbell** [comment]
Ping @rogeriopradoj.

**Comment by rogeriopradoj** [comment]
@GrahamCampbell , can you revert the last changes made by other people?

https://github.com/CHH/php-build/wiki/Home/_history

Please, try there, ok? If you can't, I'll do, right?

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/V352

**Comment by GrahamCampbell** [comment]
Fixed from the gui.

**Comment by rogeriopradoj** [comment]
:-)
